from typing import Dict

# Shared alias maps used across flight/hotel/rental parsing.
# Keep this file UTF-8 and avoid per-module hardcoded copies.

LOCATION_ALIASES: Dict[str, str] = {
    # KR
    "서울": "SEL",
    "인천": "ICN",
    "김포": "GMP",
    "부산": "PUS",
    "제주": "CJU",
    # JP
    "도쿄": "TYO",
    "오사카": "OSA",
    "후쿠오카": "FUK",
    "삿포로": "SPK",
    "나리타": "NRT",
    "하네다": "HND",
    # US/EU/APAC
    "뉴욕": "NYC",
    "런던": "LON",
    "파리": "PAR",
    "로마": "ROM",
    "방콕": "BKK",
    "다낭": "DAD",
    "하노이": "HAN",
    "호치민": "SGN",
    "싱가포르": "SIN",
    "시드니": "SYD",
    "멜버른": "MEL",
    "브리즈번": "BNE",
    # EN
    "seoul": "SEL",
    "incheon": "ICN",
    "gimpo": "GMP",
    "busan": "PUS",
    "jeju": "CJU",
    "tokyo": "TYO",
    "osaka": "OSA",
    "fukuoka": "FUK",
    "sapporo": "SPK",
    "narita": "NRT",
    "haneda": "HND",
    "new york": "NYC",
    "newyork": "NYC",
    "london": "LON",
    "paris": "PAR",
    "rome": "ROM",
    "bangkok": "BKK",
    "danang": "DAD",
    "hanoi": "HAN",
    "hochiminh": "SGN",
    "hochiminhcity": "SGN",
    "saigon": "SGN",
    "singapore": "SIN",
    "sydney": "SYD",
    "melbourne": "MEL",
    "brisbane": "BNE",
}

COUNTRY_ALIASES: Dict[str, str] = {
    "한국": "SEL",
    "대한민국": "SEL",
    "일본": "TYO",
    "중국": "BJS",
    "대만": "TPE",
    "홍콩": "HKG",
    "미국": "NYC",
    "영국": "LON",
    "프랑스": "PAR",
    "이탈리아": "ROM",
    "태국": "BKK",
    "베트남": "SGN",
    "싱가포르": "SIN",
    "말레이시아": "KUL",
    "인도": "DEL",
    "인도네시아": "JKT",
    "필리핀": "MNL",
    "호주": "SYD",
    "뉴질랜드": "AKL",
    "india": "DEL",
    "japan": "TYO",
    "korea": "SEL",
    "south korea": "SEL",
    "united states": "NYC",
    "usa": "NYC",
    "uk": "LON",
    "united kingdom": "LON",
    "france": "PAR",
    "thailand": "BKK",
    "vietnam": "SGN",
    "singapore": "SIN",
    "malaysia": "KUL",
    "philippines": "MNL",
    "australia": "SYD",
    "new zealand": "AKL",
}

HOTEL_AREA_CITY_ALIASES: Dict[str, str] = {
    # KR
    "강남": "서울",
    "홍대": "서울",
    "명동": "서울",
    "해운대": "부산",
    # JP
    "시부야": "도쿄",
    "신주쿠": "도쿄",
    "긴자": "도쿄",
    "나리타": "도쿄",
    "난바": "오사카",
    "도톤보리": "오사카",
    "우메다": "오사카",
    "shibuya": "tokyo",
    "shinjuku": "tokyo",
    "ginza": "tokyo",
    "namba": "osaka",
    "dotonbori": "osaka",
    "umeda": "osaka",
    # US
    "맨해튼": "뉴욕",
    "타임스퀘어": "뉴욕",
    "brooklyn": "new york",
    "manhattan": "new york",
    "times square": "new york",
    # EU
    "몽마르트": "파리",
    "marais": "paris",
    "soho": "london",
    "camden": "london",
}
